name: II2201
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - ale-py==0.11.2
      - asitop==0.0.24
      - attrs==25.4.0
      - blessed==1.25.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - dashing==0.1.0
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-tree==0.1.9
      - etils==1.13.0
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - glfw==2.10.0
      - grad-cam==1.5.5
      - grpcio==1.76.0
      - gym-notices==0.1.0
      - gymnasium==1.2.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpi4py==4.1.1
      - mpmath==1.3.0
      - mujoco==3.3.7
      - networkx==3.6
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - pygame==2.6.1
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shimmy==2.0.0
      - six==1.17.0
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - ttach==0.0.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: /Users/unicorn/anaconda3/envs/II2201
